name: Build prometheus telegram bot image

env:
  REGISTRY: docker.pkg.github.com
  IMAGE_NAME: prombot
  IMAGE_TAG: latest
  QUAY_REPO: quay.io/kubernetes-operators
on:
  push:
    paths:
      - '**/Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
#
#      - name: Login to github docker registry
#        run: docker login $REGISTRY  -u ${GITHUB_ACTOR} -p ${{ secrets.GITHUB_TOKEN }}
#
#      - name: Build the Docker image
#        run:  |
#             docker build --tag $REGISTRY/$GITHUB_REPOSITORY/$IMAGE_NAME:$IMAGE_TAG \
#                          --tag $REGISTRY/$GITHUB_REPOSITORY/$IMAGE_NAME:$GITHUB_SHA \
#                          --tag $QUAY_REPO/$IMAGE_NAME:$GITHUB_SHA .
#
#      - name: Push image
#        run: docker push $REGISTRY/$GITHUB_REPOSITORY/$IMAGE_NAME:$IMAGE_TAG
#
#      - name: Get quay.io credentials
#        run: echo -n ${{ secrets.QUAY_DOCKER_CFG }} | base64 -d  > ~/.docker/config.json
#
#      - name: Push to quay.io
#        run: docker push $QUAY_REPO/$IMAGE_NAME:$IMAGE_TAG

